###
POST http://localhost:8080/models
X-TenantId: tenant1

###

GET http://localhost:8080/tenants

###

PUT http://localhost:8080/tenants/tenant3
Content-Type: application/json

{
  "url": "jdbc:postgresql://localhost:5432/tenant3",
  "username": "postgres",
  "password": "postgres"
}

###

POST http://localhost:8080/models
X-TenantId: tenant3

###
